In [1]:
import numpy as np

In [2]:
myarr = np.array([1,2,3,4,5])

In [3]:
myarr


array([1, 2, 3, 4, 5])

In [4]:
myarr = np.array([1,2,390,4,5], np.float32)

In [5]:
myarr

array([  1.,   2., 390.,   4.,   5.], dtype=float32)

In [6]:
myarry = np.array([[1,2,3,4]])

In [7]:
myarry[0]

array([1, 2, 3, 4])

In [8]:
myarry[0,1]

2

In [9]:
myarry.shape

(1, 4)

In [10]:
myarry.size

4

In [11]:
myarry[0,1] = 45

In [12]:
myarry

array([[ 1, 45,  3,  4]])

In [13]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
listarray = np.array(x)

In [15]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarray.size

9

In [17]:
listarray.ndim

2

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.dtype

dtype('int32')

In [20]:
zero = np.zeros((2,3))

In [21]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(5,50,10)

In [24]:
lspace

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [25]:
np.empty(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.empty((4,5))

array([[4.24399158e-314, 9.88131292e-324, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [27]:
emt_like = np.empty_like(listarray)

In [28]:
emt_like

array([[-1784316296,       32760,  -541699824],
       [        490,  -541700784,         490],
       [ -541701360,         490,           0]])

In [29]:
ide = np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
arr = np.arange(99)

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [34]:
arr = arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
ar = np.array(x)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar.sum(axis = 0)

array([12, 15, 18])

In [40]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [41]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
ar.flat

In [43]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [44]:
ar.nbytes

36

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.argmax()

8

In [47]:
ar.argmin()

0

In [48]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [49]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [50]:
ar2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ar2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [53]:
ar + ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [54]:
ar - ar2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [55]:
ar*ar2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [56]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [57]:
np.where(5 > ar)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar3 = np.identity(3)

In [60]:
ar3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.count_nonzero(ar3)

3

In [62]:
np.nonzero(ar3)

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [63]:
import sys 

In [64]:
pyar = [1,3,5]

In [65]:
npar = np.array(pyar, np.float64)

In [66]:
sys.getsizeof(20)*len(pyar)

84

In [67]:
npar.itemsize*npar.size

24